In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
arr3 = np.zeros((3, 3))  # 3x3 array of zeros
arr4 = np.arange(0, 10, 2)  # Array from 0 to 10 (step 2)

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Zeros Array:\n", arr3)
print("Range Array:", arr4)

# Basic operations
print("\nBasic Operations:")
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Element-wise multiplication:", arr1 * 2)
print("Matrix multiplication:\n", np.dot(arr2, arr2.T))

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Range Array: [0 2 4 6 8]

Basic Operations:
Sum: 15
Mean: 3.0
Max: 5
Element-wise multiplication: [ 2  4  6  8 10]
Matrix multiplication:
 [[14 32]
 [32 77]]
