**welcome to numpy tutorial**

In [2]:
import numpy as np

In [3]:
myarr = np.array([[2,53,26,74]] , np.int64)


In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0,1] = 23

In [7]:
myarr

array([[ 2, 23, 26, 74]], dtype=int64)

In [8]:
listarray = np.array([[48,38,83], [88,29,92] , [84,75,98]])

In [9]:
listarray

array([[48, 38, 83],
       [88, 29, 92],
       [84, 75, 98]])

In [10]:
listarray.size

9

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int32')

In [13]:
np.array({38,38,38})

array({38}, dtype=object)

In [14]:
zeros = np.zeros((3,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rang = np.arange(10)

In [17]:
rang

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ones = np.ones(5)

In [19]:
ones

array([1., 1., 1., 1., 1.])

In [20]:
#use of linspace 
linspace = np.linspace(1,36,15)

In [21]:
linspace

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5, 31. , 33.5, 36. ])

In [22]:
#emp
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 7.56601165e-307],
       [1.69118787e-306, 9.34609790e-307, 1.33511562e-306,
        6.89805151e-307, 7.56592338e-307, 6.89807188e-307],
       [1.11260144e-306, 1.42418172e-306, 1.37961641e-306,
        9.45699679e-308, 2.22522596e-306, 2.10077583e-312]])

In [24]:
emp_like = np.empty_like(9)

In [25]:
emp_like

array(0)

In [26]:
ide = np.identity(34)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(34, 34)

In [29]:
ide.size

1156

In [30]:
ide.dtype

dtype('float64')

In [31]:
arr = np.arange(88)


In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [33]:
 arr.reshape(2,44)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [35]:
arr = arr.ravel()

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [37]:
x = [[3,5,3],[2,6,4],[6,5,4]]

In [38]:
arr = np.array(x)

In [39]:
arr

array([[3, 5, 3],
       [2, 6, 4],
       [6, 5, 4]])

In [40]:
arr.sum(axis=0)

array([11, 16, 11])

In [41]:
arr.sum(axis=1)

array([11, 12, 15])

In [42]:
arr.T

array([[3, 2, 6],
       [5, 6, 5],
       [3, 4, 4]])

In [43]:
arr.flat

In [44]:
for item in arr.flat:
 print(item)

3
5
3
2
6
4
6
5
4


In [45]:
arr.ndim

2

In [46]:
arr.shape

(3, 3)

In [47]:
arr.size

9

In [48]:
arr.nbytes

36

In [49]:
one = np.array([23,45,634,2])

In [50]:
one.argmax()

2

In [51]:
one.argmin()

3

In [52]:
one.argsort()

array([3, 0, 1, 2], dtype=int64)

In [53]:
arr.argmax()

4

In [54]:
arr.argmin()

3

In [55]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [56]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [57]:
arr.argsort(axis=0)

array([[1, 0, 0],
       [0, 2, 1],
       [2, 1, 2]], dtype=int64)

In [58]:
arr.argsort(axis=1)

array([[0, 2, 1],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [59]:
arr.ravel()

array([3, 5, 3, 2, 6, 4, 6, 5, 4])

In [60]:
arr

array([[3, 5, 3],
       [2, 6, 4],
       [6, 5, 4]])

In [61]:
arr2 = np.array ([[1,2,3]
                 ,[4,2,1],
                 [3,2,1]])

In [62]:
 arr + arr2

array([[4, 7, 6],
       [6, 8, 5],
       [9, 7, 5]])

In [63]:
arr * arr2

array([[ 3, 10,  9],
       [ 8, 12,  4],
       [18, 10,  4]])

In [64]:
np.sqrt(arr)

array([[1.73205081, 2.23606798, 1.73205081],
       [1.41421356, 2.44948974, 2.        ],
       [2.44948974, 2.23606798, 2.        ]])

In [65]:
arr.sum()

38

In [66]:
arr.max()


6

In [135]:
arr.min()

2

In [137]:
arr

array([[3, 5, 3],
       [2, 6, 4],
       [6, 5, 4]])

In [139]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([1, 0], dtype=int64))

In [141]:
np.count_nonzero(arr)

9

In [143]:
arr [1,2] = 0

In [145]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))