In [1]:
import numpy as np 


In [5]:
arr = np.array([[34,54,23],[45,65,23],[23,56,36]])

In [7]:
arr

array([[34, 54, 23],
       [45, 65, 23],
       [23, 56, 36]])

In [9]:
print("shape",arr.shape)

shape (3, 3)


In [11]:
print("data type",arr.dtype)

data type int32


In [13]:
print("first row:",arr[0,:])

first row: [34 54 23]


In [19]:
print("theird column:",arr[:,2])

theird column: [23 23 36]


In [21]:
print("center 2x2:",arr [1:3,1:3])

center 2x2: [[65 23]
 [56 36]]


In [35]:
print("reshaped", arr.reshape(3,3))

reshaped [[34 54 23]
 [45 65 23]
 [23 56 36]]


In [47]:
print("reshaped to 3x3:",arr.reshape(3,3))

reshaped to 3x3: [[34 54 23]
 [45 65 23]
 [23 56 36]]


In [49]:
print("add 10:",arr+10)

add 10: [[44 64 33]
 [55 75 33]
 [33 66 46]]


In [55]:
print("row multiplication:",arr*np.array([1,2,4]))


row multiplication: [[ 34 108  92]
 [ 45 130  92]
 [ 23 112 144]]


In [65]:
column = arr.mean(axis=1)
print("subtract column means:",arr-column)

subtract column means: [[ -3.           9.66666667 -15.33333333]
 [  8.          20.66666667 -15.33333333]
 [-14.          11.66666667  -2.33333333]]


In [77]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("elementwise multiplication", a * b)

elementwise multiplication [[ 5 12]
 [21 32]]


In [79]:
print("matrix multiplication",np.dot(a,b))

matrix multiplication [[19 22]
 [43 50]]


In [85]:
print("vertical stack",np.vstack((a,b)))

vertical stack [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
print("element >5",arr[arr>5])

element >5 [34 54 23 45 65 23 23 56 36]


In [89]:
print("square roots:",np.sqrt(arr))

square roots: [[5.83095189 7.34846923 4.79583152]
 [6.70820393 8.06225775 4.79583152]
 [4.79583152 7.48331477 6.        ]]


In [91]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
subset = matrix[:2, :] 
col_means = matrix.mean(axis=0)
normalized = matrix - col_means